id: PF38FA80B
initial_creation_type: ocr
source_metadata:
  volumes:
    188b1a45e1e44ee3bba1aff3a9aef547:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ལྷོ་ཟ་མོ་ཚངས་དབྱངས་ལ་སྡུག་བསྔལ་གྱི་བྱེ་བྲག་བསྟན་པ།
      total_pages: 1144
      volume_number: 96
